version: '3.7'

services:
  database_rentalx:
    image: postgres
    container_name: database_rentalx
    restart: always
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - pgdata:/data/postgres
    network_mode: host

  app:
    build: .
    container_name: rentalx
    volumes:
      - .:/usr/app
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    network_mode: host
    depends_on:
      - database_rentalx
    command: ["./wait-for-it.sh", "database_rentalx:5432", "--", "npm", "run", "dev"]

volumes:
  pgdata:
    driver: local